spring.application.name=springboot-comprehensive-exercise
spring.datasource.url=jdbc:postgresql://localhost:5432/training
spring.datasource.username=docker
spring.datasource.password=docker

spring.messages.basename=i18n/messages

spring.jpa.show-sql=true

spring.thymeleaf.cache=false
server.port=8081